mappings:
  GiftVoucherProductPage_Controller: Sunnysideup\EcommerceGiftvoucher\GiftVoucherProductPageController
  GiftVoucherProductPage: Sunnysideup\EcommerceGiftvoucher\GiftVoucherProductPage
  GiftVoucherProductPage_ProductOrderItem: Sunnysideup\EcommerceGiftvoucher\Model\GiftVoucherProductPageProductOrderItem
